applied shellcheck fixes

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -5,7 +5,7 @@ export BATS_VERSION='1.11.1'
 VALID_FORMATTERS="pretty, junit, tap, tap13"
 
 version() {
-  printf 'Bats %s\n' "$BATS_VERSION"
+  printf 'Bats %s\n' "${BATS_VERSION}"
 }
 
 abort() {
@@ -15,7 +15,7 @@ abort() {
     shift
   fi
   printf 'Error: %s\n' "$1" >&2
-  if [[ -n $print_usage ]]; then
+  if [[ -n ${print_usage} ]]; then
     usage >&2
   fi
   exit 1
@@ -38,14 +38,14 @@ HELP_TEXT_HEADER
   -c, --count               Count test cases without running any tests
   --code-quote-style <style>
                             A two character string of code quote delimiters
-                            or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and
-                            $BATS_END_CODE_QUOTE. Can also be set via $BATS_CODE_QUOTE_STYLE
+                            or 'custom' which requires setting ${BATS_BEGIN_CODE_QUOTE} and
+                            ${BATS_END_CODE_QUOTE}. Can also be set via ${BATS_CODE_QUOTE_STYLE}
   --line-reference-format   Controls how file/line references e.g. in stack traces are printed:
                               - comma_line (default): a.bats, line 1
                               - colon:  a.bats:1
                               - uri: file:///tests/a.bats:1
                               - custom: provide your own via defining bats_format_file_line_reference_custom
-                                        with parameters <filename> <line>, store via `printf -v "$output"`
+                                        with parameters <filename> <line>, store via `printf -v "${output}"`
   -f, --filter <regex>      Only run tests that match the regular expression
   --filter-status <status>  Only run tests with the given status in the last completed (no CTRL+C/SIGINT) run.
                             Valid <status> values are:
@@ -74,14 +74,14 @@ HELP_TEXT_HEADER
   --report-formatter <type> Switch between reporters (same options as --formatter)
   -o, --output <dir>        Directory to write report files (must exist)
   -p, --pretty              Shorthand for "--formatter pretty"
-  --print-output-on-failure Automatically print the value of `$output` on failed tests
+  --print-output-on-failure Automatically print the value of `${output}` on failed tests
   -r, --recursive           Include tests in subdirectories
   --show-output-of-passing-tests
                             Print output of passing tests
   -t, --tap                 Shorthand for "--formatter tap"
   -T, --timing              Add timing information to tests
   -x, --trace               Print test commands as they are executed (like `set -x`)
-  --verbose-run             Make `run` print `$output` by default
+  --verbose-run             Make `run` print `${output}` by default
   -v, --version             Display the version number
 
   For more information, see https://github.com/bats-core/bats-core
@@ -91,20 +91,20 @@ HELP_TEXT_BODY
 expand_path() {
   local path="${1%/}"
   local dirname="${path%/*}"
-  if [[ -z "$dirname" ]]; then
+  if [[ -z "${dirname}" ]]; then
     dirname=/
   fi
   local result="$2"
-  local OLDPWD="$PWD"
+  local OLDPWD="${PWD}"
 
-  if [[ "$dirname" == "$path" ]]; then
-    dirname="$PWD"
+  if [[ "${dirname}" == "${path}" ]]; then
+    dirname="${PWD}"
   else
-    cd "$dirname"
-    dirname="$PWD"
-    cd "$OLDPWD"
+    cd "${dirname}"
+    dirname="${PWD}"
+    cd "${OLDPWD}"
   fi
-  printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
+  printf -v "${result}" '%s/%s' "${dirname}" "${path##*/}"
 }
 
 BATS_LIBEXEC="$(
@@ -112,8 +112,8 @@ BATS_LIBEXEC="$(
   pwd
 )"
 export BATS_LIBEXEC
-export BATS_CWD="$PWD"
-export PATH="$BATS_LIBEXEC:$PATH"
+export BATS_CWD="${PWD}"
+export PATH="${BATS_LIBEXEC}:${PATH}"
 export BATS_ROOT_PID=$$
 export BATS_TMPDIR="${TMPDIR:-/tmp}"
 BATS_TMPDIR=${BATS_TMPDIR%/} # chop off trailing / to avoid duplication
@@ -138,21 +138,21 @@ single_char_flags="hvcprtTx"
 
 # Unpack single-character options bundled together, e.g. -cr, -pr.
 for arg in "$@"; do
-  if [[ "$arg" =~ ^-[^-]. ]]; then
+  if [[ "${arg}" =~ ^-[^-]. ]]; then
     index=1
     while option="${arg:$((index++)):1}"; do
-      if [[ -z "$option" ]]; then
+      if [[ -z "${option}" ]]; then
         break
       fi
-      if [[ "$single_char_flags" != *$option* && -n "${arg:index}" ]]; then
-        printf "Error: -%s is not allowed within pack of flags.\n" "$option"
+      if [[ "${single_char_flags}" != *${option}* && -n "${arg:index}" ]]; then
+        printf "Error: -%s is not allowed within pack of flags.\n" "${option}"
         printf "       Please put it last (e.g. \`-rF junit\` instead of \`-Fr junit\`), or on its own (\`-r -F junit\`)!\n"
         exit 1
       fi
-      arguments+=("-$option")
+      arguments+=("-${option}")
     done
   else
-    arguments+=("$arg")
+    arguments+=("${arg}")
   fi
   shift
 done
@@ -265,14 +265,14 @@ while [[ "$#" -ne 0 ]]; do
   --gather-test-outputs-in)
     shift
     output_dir="$1"
-    if [ -d "$output_dir" ]; then
-      if ! find "$output_dir" -mindepth 1 -exec false {} + 2>/dev/null; then
-        abort --no-print-usage "Directory '$output_dir' must be empty for --gather-test-outputs-in"
+    if [ -d "${output_dir}" ]; then
+      if ! find "${output_dir}" -mindepth 1 -exec false {} + 2>/dev/null; then
+        abort --no-print-usage "Directory '${output_dir}' must be empty for --gather-test-outputs-in"
       fi
-    elif ! mkdir "$output_dir" 2>/dev/null; then
-      abort --no-print-usage "Could not create '$output_dir' for --gather-test-outputs-in"
+    elif ! mkdir "${output_dir}" 2>/dev/null; then
+      abort --no-print-usage "Could not create '${output_dir}' for --gather-test-outputs-in"
     fi
-    flags+=(--gather-test-outputs-in "$output_dir")
+    flags+=(--gather-test-outputs-in "${output_dir}")
     ;;
   --setup-suite-file)
     shift
@@ -304,17 +304,17 @@ while [[ "$#" -ne 0 ]]; do
   shift
 done
 
-if [[ ! $BATS_LINE_REFERENCE_FORMAT =~ (custom|comma_line|colon|uri) ]]; then
-  abort "Invalid BATS_LINE_REFERENCE_FORMAT '$BATS_LINE_REFERENCE_FORMAT' (e.g. via --line-reference-format)"
+if [[ ! ${BATS_LINE_REFERENCE_FORMAT} =~ (custom|comma_line|colon|uri) ]]; then
+  abort "Invalid BATS_LINE_REFERENCE_FORMAT '${BATS_LINE_REFERENCE_FORMAT}' (e.g. via --line-reference-format)"
 fi
 
 if [[ -n "${BATS_RUN_TMPDIR:-}" ]]; then
-  if [[ -d "$BATS_RUN_TMPDIR" ]]; then
-    printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
+  if [[ -d "${BATS_RUN_TMPDIR}" ]]; then
+    printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "${BATS_RUN_TMPDIR}" >&2
     printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
     exit 1
-  elif ! mkdir -p "$BATS_RUN_TMPDIR"; then
-    printf "Error: Failed to create BATS_RUN_TMPDIR (%s)\n" "$BATS_RUN_TMPDIR" >&2
+  elif ! mkdir -p "${BATS_RUN_TMPDIR}"; then
+    printf "Error: Failed to create BATS_RUN_TMPDIR (%s)\n" "${BATS_RUN_TMPDIR}" >&2
     exit 1
   fi
 elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-XXXXXX"); then
@@ -325,66 +325,66 @@ fi
 export BATS_WARNING_FILE="${BATS_RUN_TMPDIR}/warnings.log"
 
 bats_exit_trap() {
-  if [[ -s "$BATS_WARNING_FILE" ]]; then
+  if [[ -s "${BATS_WARNING_FILE}" ]]; then
     local pre_cat='' post_cat=''
-    if [[ $formatter == pretty ]]; then
+    if [[ ${formatter} == pretty ]]; then
       pre_cat=$'\x1B[31m'
       post_cat=$'\x1B[0m'
     fi
-    printf "\nThe following warnings were encountered during tests:\n%s" "$pre_cat"
-    cat "$BATS_WARNING_FILE"
-    printf "%s" "$post_cat"
+    printf "\nThe following warnings were encountered during tests:\n%s" "${pre_cat}"
+    cat "${BATS_WARNING_FILE}"
+    printf "%s" "${post_cat}"
   fi >&2
 
-  if [[ -n "$BATS_TEMPDIR_CLEANUP" ]]; then
-    rm -rf "$BATS_RUN_TMPDIR"
+  if [[ -n "${BATS_TEMPDIR_CLEANUP}" ]]; then
+    rm -rf "${BATS_RUN_TMPDIR}"
   else
-    printf "BATS_RUN_TMPDIR: %s\n" "$BATS_RUN_TMPDIR" >&2
+    printf "BATS_RUN_TMPDIR: %s\n" "${BATS_RUN_TMPDIR}" >&2
   fi
 }
 
 trap bats_exit_trap EXIT
 
-if [[ "$formatter" != "tap" ]]; then
+if [[ "${formatter}" != "tap" ]]; then
   flags+=('-x')
 fi
 
-if [[ -n "$report_formatter" && "$report_formatter" != "tap" ]]; then
+if [[ -n "${report_formatter}" && "${report_formatter}" != "tap" ]]; then
   flags+=('-x')
 fi
 
-if [[ "$formatter" == "junit" ]]; then
+if [[ "${formatter}" == "junit" ]]; then
   flags+=('-T')
   formatter_flags+=('--base-path' "${arguments[0]}")
 fi
-if [[ "$report_formatter" == "junit" ]]; then
+if [[ "${report_formatter}" == "junit" ]]; then
   flags+=('-T')
   report_formatter_flags+=('--base-path' "${arguments[0]}")
 fi
 
-if [[ "$formatter" == "pretty" ]]; then
+if [[ "${formatter}" == "pretty" ]]; then
   formatter_flags+=('--base-path' "${arguments[0]}")
 fi
 
 # if we don't need to filter extended syntax, use the faster formatter
-if [[ "$formatter" == tap && -z "$report_formatter" ]]; then
+if [[ "${formatter}" == tap && -z "${report_formatter}" ]]; then
   formatter="cat"
 fi
 
 bats_check_formatter() { # <formatter-path>
   local -r formatter="$1"
-  if [[ ! -f "$formatter" ]]; then
-    printf "ERROR: Formatter '%s' is not readable!\n" "$formatter"
+  if [[ ! -f "${formatter}" ]]; then
+    printf "ERROR: Formatter '%s' is not readable!\n" "${formatter}"
     exit 1
-  elif [[ ! -x "$formatter" ]]; then
-    printf "ERROR: Formatter '%s' is not executable!\n" "$formatter"
+  elif [[ ! -x "${formatter}" ]]; then
+    printf "ERROR: Formatter '%s' is not executable!\n" "${formatter}"
     exit 1
   fi
 }
 
-if [[ $formatter == /* ]]; then # absolute paths are direct references to formatters
-  bats_check_formatter "$formatter"
-  interpolated_formatter="$formatter"
+if [[ ${formatter} == /* ]]; then # absolute paths are direct references to formatters
+  bats_check_formatter "${formatter}"
+  interpolated_formatter="${formatter}"
 else
   interpolated_formatter="bats-format-${formatter}"
 fi
@@ -393,13 +393,13 @@ if [[ "${#arguments[@]}" -eq 0 ]]; then
   abort 'Must specify at least one <test>'
 fi
 
-if [[ -n "$report_formatter" ]]; then
+if [[ -n "${report_formatter}" ]]; then
   if [[ ! -w "${BATS_REPORT_OUTPUT_DIR}" ]]; then
     abort "Output path ${BATS_REPORT_OUTPUT_DIR} is not writeable"
   fi
   # only set BATS_REPORT_FILENAME if none was given
   if [[ -z "${BATS_REPORT_FILENAME:-}" ]]; then
-    case "$report_formatter" in
+    case "${report_formatter}" in
     tap | tap13)
       BATS_REPORT_FILENAME="report.tap"
       ;;
@@ -413,8 +413,8 @@ if [[ -n "$report_formatter" ]]; then
   fi
 fi
 
-if [[ $report_formatter == /* ]]; then # absolute paths are direct references to formatters
-  bats_check_formatter "$report_formatter"
+if [[ ${report_formatter} == /* ]]; then # absolute paths are direct references to formatters
+  bats_check_formatter "${report_formatter}"
   interpolated_report_formatter="${report_formatter}"
 else
   interpolated_report_formatter="bats-format-${report_formatter}"
@@ -438,54 +438,54 @@ custom)
   fi
   ;;
 *)
-  printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE" >&2
+  printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "${BATS_CODE_QUOTE_STYLE}" >&2
   exit 1
   ;;
 esac
 
-if [[ -n "$setup_suite_file" && ! -f "$setup_suite_file" ]]; then
-  abort "--setup-suite-file $setup_suite_file does not exist!"
+if [[ -n "${setup_suite_file}" && ! -f "${setup_suite_file}" ]]; then
+  abort "--setup-suite-file ${setup_suite_file} does not exist!"
 fi
 
 filenames=()
 for filename in "${arguments[@]}"; do
-  expand_path "$filename" 'filename'
+  expand_path "${filename}" 'filename'
 
-  if [[ -z "$setup_suite_file" ]]; then
-    if [[ -d "$filename" ]]; then
-      dirname="$filename"
+  if [[ -z "${setup_suite_file}" ]]; then
+    if [[ -d "${filename}" ]]; then
+      dirname="${filename}"
     else
       dirname="${filename%/*}"
     fi
-    potential_setup_suite_file="$dirname/setup_suite.bash"
-    if [[ -e "$potential_setup_suite_file" ]]; then
-      setup_suite_file="$potential_setup_suite_file"
+    potential_setup_suite_file="${dirname}/setup_suite.bash"
+    if [[ -e "${potential_setup_suite_file}" ]]; then
+      setup_suite_file="${potential_setup_suite_file}"
     fi
   fi
 
-  if [[ -d "$filename" ]]; then
+  if [[ -d "${filename}" ]]; then
     shopt -s nullglob
-    if [[ "$recursive" -eq 1 ]]; then
+    if [[ "${recursive}" -eq 1 ]]; then
       while IFS= read -r -d $'\0' file; do
-        filenames+=("$file")
-      done < <(find -L "$filename" -type f -name "*.${BATS_FILE_EXTENSION:-bats}" -print0 | sort -z)
+        filenames+=("${file}")
+      done < <(find -L "${filename}" -type f -name "*.${BATS_FILE_EXTENSION:-bats}" -print0 | sort -z)
     else
-      for suite_filename in "$filename"/*."${BATS_FILE_EXTENSION:-bats}"; do
-        filenames+=("$suite_filename")
+      for suite_filename in "${filename}"/*."${BATS_FILE_EXTENSION:-bats}"; do
+        filenames+=("${suite_filename}")
       done
     fi
     shopt -u nullglob
   else
-    filenames+=("$filename")
+    filenames+=("${filename}")
   fi
 done
 
-if [[ -n "$setup_suite_file" ]]; then
-  flags+=("--setup-suite-file" "$setup_suite_file")
+if [[ -n "${setup_suite_file}" ]]; then
+  flags+=("--setup-suite-file" "${setup_suite_file}")
 fi
 
 # shellcheck source=lib/bats-core/validator.bash
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/validator.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/validator.bash"
 
 trap 'BATS_INTERRUPTED=true' INT # let the lower levels handle the interruption
 
@@ -497,20 +497,20 @@ bats_tee() { # <output-file> <command...>
   local output_file=$1 status=0
   shift
   exec 3<&1 # use FD3 to get around pipe
-  tee >(cat >&3) | "$@" >"$output_file" || status=$?
+  tee >(cat >&3) | "$@" >"${output_file}" || status=$?
   if (( status != 0 )); then
-    printf "ERROR: command \`%s\` failed with status %d\n" "$*" "$status" >&2
+    printf "ERROR: command \`%s\` failed with status %d\n" "$*" "${status}" >&2
   fi
-  return $status
+  return "${status}"
 }
 
-if [[ -n "$report_formatter" ]]; then
+if [[ -n "${report_formatter}" ]]; then
   exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
-    bats_tee "${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}" "$interpolated_report_formatter" "${report_formatter_flags[@]}" |
+    bats_tee "${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}" "${interpolated_report_formatter}" "${report_formatter_flags[@]}" |
     bats_test_count_validator |
-    "$interpolated_formatter" "${formatter_flags[@]}"
+    "${interpolated_formatter}" "${formatter_flags[@]}"
 else
   exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
     bats_test_count_validator |
-    "$interpolated_formatter" "${formatter_flags[@]}"
+    "${interpolated_formatter}" "${formatter_flags[@]}"
 fi
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -54,24 +54,24 @@ export BATS_TEST_FILE_NUMBER="$1"
 filename="$2"
 TESTS_FILE="$3"
 
-if [[ ! -f "$filename" ]]; then
-  printf 'Testfile "%s" not found\n' "$filename" >&2
+if [[ ! -f "${filename}" ]]; then
+  printf 'Testfile "%s" not found\n' "${filename}" >&2
   exit 1
 fi
 
-export BATS_TEST_FILENAME="$filename"
+export BATS_TEST_FILENAME="${filename}"
 
 # shellcheck source=lib/bats-core/preprocessing.bash
 # shellcheck disable=SC2153
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/preprocessing.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/preprocessing.bash"
 
 bats_run_setup_file() {
   # shellcheck source=lib/bats-core/tracing.bash
   # shellcheck disable=SC2153
-  source "$BATS_ROOT/$BATS_LIBDIR/bats-core/tracing.bash"
+  source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/tracing.bash"
   # shellcheck source=lib/bats-core/test_functions.bash
   # shellcheck disable=SC2153
-  source "$BATS_ROOT/$BATS_LIBDIR/bats-core/test_functions.bash"
+  source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/test_functions.bash"
 
   _bats_test_functions_setup -1 # invalid TEST_NUMBER, as this is not a test
 
@@ -89,19 +89,19 @@ bats_run_setup_file() {
   # shellcheck disable=2034
   BATS_ERROR_STATUS= # used in tracing.bash
   
-  touch "$BATS_OUT"
+  touch "${BATS_OUT}"
   bats_setup_tracing
   trap 'bats_file_teardown_trap' EXIT
 
   local status=0
   # get the setup_file/teardown_file functions for this file (if it has them)
   # shellcheck disable=SC1090
-  source "$BATS_TEST_SOURCE"
+  source "${BATS_TEST_SOURCE}"
 
   BATS_SOURCE_FILE_COMPLETED=1
 
   bats_set_stacktrace_limit
-  setup_file >>"$BATS_OUT" 2>&1
+  setup_file >>"${BATS_OUT}" 2>&1
 
   BATS_SETUP_FILE_COMPLETED=1
 }
@@ -114,14 +114,14 @@ bats_run_teardown_file() {
   bats_set_stacktrace_limit
 
   # rely on bats_error_trap to catch failures
-  teardown_file >>"$BATS_OUT" 2>&1 || bats_teardown_file_status=$?
+  teardown_file >>"${BATS_OUT}" 2>&1 || bats_teardown_file_status=$?
 
   if ((bats_teardown_file_status == 0)); then
     BATS_TEARDOWN_FILE_COMPLETED=1
   elif [[ -n "${BATS_SETUP_FILE_COMPLETED:-}" ]]; then
     BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=1
-    BATS_ERROR_STATUS=$bats_teardown_file_status
-    return $BATS_ERROR_STATUS
+    BATS_ERROR_STATUS=${bats_teardown_file_status}
+    return "${BATS_ERROR_STATUS}"
   fi
 }
 
@@ -132,13 +132,13 @@ bats_file_teardown_trap() {
 }
 
 # shellcheck source=lib/bats-core/common.bash
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/common.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/common.bash"
 
 # shellcheck disable=SC2317
 bats_file_exit_trap() {
   local -r last_return_code=$?
   if [[ ${1:-} != in-teardown_trap ]]; then
-    BATS_ERROR_STATUS=$last_return_code
+    BATS_ERROR_STATUS=${last_return_code}
   fi
   trap - ERR EXIT
   local failure_reason
@@ -148,33 +148,33 @@ bats_file_exit_trap() {
     # print skip message for each test (use this to avoid reimplementing filtering)
     bats_run_tests 1<&3 # restore original stdout (this is running in setup_file's redirection to BATS_OUT)
     bats_exec_file_status=0 # this should not lead to errors
-  elif [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
-    if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
+  elif [[ -z "${BATS_SETUP_FILE_COMPLETED}" || -z "${BATS_TEARDOWN_FILE_COMPLETED}" ]]; then
+    if [[ -z "${BATS_SETUP_FILE_COMPLETED}" ]]; then
       failure_reason='setup_file'
-    elif [[ -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+    elif [[ -z "${BATS_TEARDOWN_FILE_COMPLETED}" ]]; then
       failure_reason='teardown_file'
       failure_test_index=$((BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + ${#tests_to_run[@]} + 1))
-    elif [[ -z "$BATS_SOURCE_FILE_COMPLETED" ]]; then
+    elif [[ -z "${BATS_SOURCE_FILE_COMPLETED}" ]]; then
       failure_reason='source'
     else
       failure_reason='unknown internal'
     fi
-    printf "not ok %d %s\n" "$failure_test_index" "$failure_reason failed" >&3
+    printf "not ok %d %s\n" "${failure_test_index}" "${failure_reason} failed" >&3
     local stack_trace
     bats_get_failure_stack_trace stack_trace
     bats_print_stack_trace "${stack_trace[@]}" >&3
     bats_print_failed_command "${stack_trace[@]}" >&3
-    bats_prefix_lines_for_tap_output <"$BATS_OUT" | bats_replace_filename >&3
-    rm -rf "$BATS_OUT"
+    bats_prefix_lines_for_tap_output <"${BATS_OUT}" | bats_replace_filename >&3
+    rm -rf "${BATS_OUT}"
     bats_exec_file_status=1
   fi
 
   # setup_file not executed but defined in this test file? -> might be defined in the wrong file
   if [[ -z "${BATS_SETUP_SUITE_COMPLETED-}" ]] && declare -F setup_suite >/dev/null; then
-    bats_generate_warning 3 --no-stacktrace "$BATS_TEST_FILENAME"
+    bats_generate_warning 3 --no-stacktrace "${BATS_TEST_FILENAME}"
   fi
 
-  exit "$bats_exec_file_status"
+  exit ""${bats_exec_file_status}""
 }
 
 function setup_file() {
@@ -188,20 +188,20 @@ function teardown_file() {
 bats_forward_output_of_parallel_test() {
   local test_number_in_suite=$1
   local status=0
-  wait "$(cat "$output_folder/$test_number_in_suite/pid")" || status=1
-  cat "$output_folder/$test_number_in_suite/stdout"
-  cat "$output_folder/$test_number_in_suite/stderr" >&2
-  return $status
+  wait "$(cat "${output_folder}/${test_number_in_suite}/pid")" || status=1
+  cat "${output_folder}/${test_number_in_suite}/stdout"
+  cat "${output_folder}/${test_number_in_suite}/stderr" >&2
+  return "${status}"
 }
 
 bats_is_next_parallel_test_finished() {
   local PID
   # get the pid of the next potentially finished test
-  PID=$(cat "$output_folder/$((test_number_in_suite_of_last_finished_test + 1))/pid")
+  PID=$(cat "${output_folder}/$((test_number_in_suite_of_last_finished_test + 1))/pid")
   # try to send a signal to this process
   # if it fails, the process exited,
   # if it succeeds, the process is still running
-  if kill -0 "$PID" 2>/dev/null; then
+  if kill -0 "${PID}" 2>/dev/null; then
     return 1
   fi
 }
@@ -216,20 +216,20 @@ bats_forward_output_for_parallel_tests() {
     # if we are okay with waiting or if the test has already been finished
     if [[ "$1" == "blocking" ]] || bats_is_next_parallel_test_finished; then
       ((++test_number_in_suite_of_last_finished_test))
-      bats_forward_output_of_parallel_test "$test_number_in_suite_of_last_finished_test" || status=$?
+      bats_forward_output_of_parallel_test "${test_number_in_suite_of_last_finished_test}" || status=$?
     else
       # non-blocking and the process has not finished -> abort the printing
       break
     fi
   done
-  return $status
+  return "${status}"
 }
 
 bats_run_test_with_retries() { # <args>
   local status=0
   local should_try_again=1 try_number
   for ((try_number = 1; should_try_again; ++try_number)); do
-    if "$BATS_LIBEXEC/bats-exec-test" "$@" "$try_number"; then
+    if "${BATS_LIBEXEC}/bats-exec-test" "$@" "${try_number}"; then
       should_try_again=0
     else
       status=$?
@@ -238,38 +238,38 @@ bats_run_test_with_retries() { # <args>
         status=0 # this is not the last try -> reset status
       else
         should_try_again=0
-        bats_exec_file_status=$status
+        bats_exec_file_status="${status}"
       fi
     fi
   done
-  return $status
+  return "${status}"
 }
 
 bats_run_tests_in_parallel() {
-  local output_folder="$BATS_RUN_TMPDIR/parallel_output"
+  local output_folder="${BATS_RUN_TMPDIR}/parallel_output"
   local status=0
-  mkdir -p "$output_folder"
+  mkdir -p "${output_folder}"
   # shellcheck source=lib/bats-core/semaphore.bash
-  source "$BATS_ROOT/$BATS_LIBDIR/bats-core/semaphore.bash"
+  source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/semaphore.bash"
   bats_semaphore_setup
   # the test_number_in_file is not yet incremented -> one before the next test to run
-  local test_number_in_suite_of_last_finished_test="$BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE" # stores which test was printed last
-  local test_number_in_file=0 test_number_in_suite=$BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE
+  local test_number_in_suite_of_last_finished_test="${BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE}" # stores which test was printed last
+  local test_number_in_file=0 test_number_in_suite=${BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE}
   for test_name in "${tests_to_run[@]}"; do
     # Only handle non-empty lines
-    if [[ $test_name ]]; then
+    if [[ ${test_name} ]]; then
       ((++test_number_in_suite))
       ((++test_number_in_file))
-      mkdir -p "$output_folder/$test_number_in_suite"
-      bats_semaphore_run "$output_folder/$test_number_in_suite" \
-        bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" "$test_number_in_suite" "$test_number_in_file" \
-        >"$output_folder/$test_number_in_suite/pid"
+      mkdir -p "${output_folder}/${test_number_in_suite}"
+      bats_semaphore_run "${output_folder}/${test_number_in_suite}" \
+        bats_run_test_with_retries "${flags[@]}" "${filename}" "${test_name}" "${test_number_in_suite}" "${test_number_in_file}" \
+        >"${output_folder}/${test_number_in_suite}/pid"
     fi
     # print results early to get interactive feedback
     bats_forward_output_for_parallel_tests non-blocking || status=1 # ignore if we did not finish yet
   done
   bats_forward_output_for_parallel_tests blocking || status=1
-  return $status
+  return "${status}"
 }
 
 bats_read_tests_list_file() {
@@ -281,19 +281,19 @@ bats_read_tests_list_file() {
     # check if the line begins with filename
     # filename might contain some hard to parse characters,
     # use simple string operations to work around that issue
-    if [[ "$filename" == "${test_line::${#filename}}" ]]; then
+    if [[ "${filename}" == "${test_line::${#filename}}" ]]; then
       # get the rest of the line without the separator \t
       test_name=${test_line:$((1 + ${#filename}))}
-      tests_to_run+=("$test_name")
+      tests_to_run+=("${test_name}")
       # save the first test's number for later iteration
       # this assumes that tests for a file are stored consecutive in the file!
-      if [[ -z "$test_number_in_suite" ]]; then
-        test_number_in_suite=$line_number
+      if [[ -z "${test_number_in_suite}" ]]; then
+        test_number_in_suite=${line_number}
       fi
     fi
     ((++line_number))
-  done <"$TESTS_FILE"
-  BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE="$test_number_in_suite"
+  done <"${TESTS_FILE}"
+  BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE="${test_number_in_suite}"
   declare -ri BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE # mark readonly (cannot merge assignment, because value would be lost)
 }
 
@@ -303,27 +303,27 @@ bats_run_tests() {
   if [[ "${BATS_RUN_TESTS_SKIPPED-}" ]]; then
     # shellcheck disable=SC2317
     bats_test_begin() {
-      printf "ok %d %s # skip %s\n" "$test_number_in_suite" "$1" "$BATS_RUN_TESTS_SKIPPED_REASON"  >&3
+      printf "ok %d %s # skip %s\n" "${test_number_in_suite}" "$1" "${BATS_RUN_TESTS_SKIPPED_REASON}"  >&3
       return 1
     }
     local test_number_in_suite=0
     for test_name in "${tests_to_run[@]}"; do
       ((++test_number_in_suite))
-      eval "$test_name" || true
+      eval "${test_name}" || true
     done
     exit 0
   fi
 
-  if [[ "$num_jobs" -lt 1 ]]; then
-    printf 'Invalid number of jobs: %s\n' "$num_jobs" >&2
+  if [[ "${num_jobs}" -lt 1 ]]; then
+    printf 'Invalid number of jobs: %s\n' "${num_jobs}" >&2
     exit 1
   fi
 
-  if [[ "$num_jobs" != 1 && "${BATS_NO_PARALLELIZE_WITHIN_FILE-False}" == False ]]; then
-    export BATS_SEMAPHORE_NUMBER_OF_SLOTS="$num_jobs"
-    bats_run_tests_in_parallel "$BATS_RUN_TMPDIR/parallel_output" || bats_exec_file_status=1
+  if [[ "${num_jobs}" != 1 && "${BATS_NO_PARALLELIZE_WITHIN_FILE-False}" == False ]]; then
+    export BATS_SEMAPHORE_NUMBER_OF_SLOTS="${num_jobs}"
+    bats_run_tests_in_parallel "${BATS_RUN_TMPDIR}/parallel_output" || bats_exec_file_status=1
   else
-    local test_number_in_suite=$BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE \
+    local test_number_in_suite=${BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE} \
       test_number_in_file=0
     for test_name in "${tests_to_run[@]}"; do
       #echo "bats-exec-file: execute test ${test_name}" >&2
@@ -335,8 +335,8 @@ bats_run_tests() {
       if [[ -n ${test_name-} ]]; then
         ((++test_number_in_suite))
         ((++test_number_in_file))
-        bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" \
-          "$test_number_in_suite" "$test_number_in_file" || bats_exec_file_status=$?
+        bats_run_test_with_retries "${flags[@]}" "${filename}" "${test_name}" \
+          "${test_number_in_suite}" "${test_number_in_file}" || bats_exec_file_status=$?
       fi
     done
   fi
@@ -344,16 +344,16 @@ bats_run_tests() {
 
 bats_create_file_tempdirs() {
   local bats_files_tmpdir="${BATS_RUN_TMPDIR}/file"
-  if ! mkdir -p "$bats_files_tmpdir"; then
-    printf 'Failed to create %s\n' "$bats_files_tmpdir" >&2
+  if ! mkdir -p "${bats_files_tmpdir}"; then
+    printf 'Failed to create %s\n' "${bats_files_tmpdir}" >&2
     exit 1
   fi
-  BATS_FILE_TMPDIR="$bats_files_tmpdir/${BATS_TEST_FILE_NUMBER?}"
-  if ! mkdir "$BATS_FILE_TMPDIR"; then
-    printf 'Failed to create BATS_FILE_TMPDIR=%s\n' "$BATS_FILE_TMPDIR" >&2
+  BATS_FILE_TMPDIR="${bats_files_tmpdir}/${BATS_TEST_FILE_NUMBER?}"
+  if ! mkdir "${BATS_FILE_TMPDIR}"; then
+    printf 'Failed to create BATS_FILE_TMPDIR=%s\n' "${BATS_FILE_TMPDIR}" >&2
     exit 1
   fi
-  ln -s "$BATS_TEST_FILENAME" "$BATS_FILE_TMPDIR-$(basename "$BATS_TEST_FILENAME").source_file"
+  ln -s "${BATS_TEST_FILENAME}" "${BATS_FILE_TMPDIR}-$(basename "${BATS_TEST_FILENAME}").source_file"
   export BATS_FILE_TMPDIR
 }
 
@@ -368,8 +368,8 @@ if [[ ${#tests_to_run[@]} -eq 0 ]]; then
   exit 0
 fi
 
-if [[ -n "$extended_syntax" ]]; then
-  printf "suite %s\n" "$filename"
+if [[ -n "${extended_syntax}" ]]; then
+  printf "suite %s\n" "${filename}"
 fi
 
 # requires the test list to be read but not empty
@@ -389,4 +389,4 @@ bats_run_tests
 trap bats_interrupt_trap INT
 bats_run_teardown_file
 
-exit $bats_exec_file_status
+exit "${bats_exec_file_status}"
diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -20,7 +20,7 @@ abort() {
 }
 
 # shellcheck source=lib/bats-core/common.bash disable=SC2153
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/common.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/common.bash"
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
@@ -34,7 +34,7 @@ while [[ "$#" -ne 0 ]]; do
   -j)
     shift
     num_jobs="$1"
-    flags+=('-j' "$num_jobs")
+    flags+=('-j' "${num_jobs}")
     ;;
   --parallel-binary-name)
     shift
@@ -92,12 +92,12 @@ while [[ "$#" -ne 0 ]]; do
   shift
 done
 
-if [[ "$num_jobs" != 1 ]]; then
-  if ! type -p "${parallel_binary_name}" >/dev/null && "${parallel_binary_name}" --version &>/dev/null && [[ -z "$bats_no_parallelize_across_files" ]]; then
+if [[ "${num_jobs}" != 1 ]]; then
+  if ! type -p "${parallel_binary_name}" >/dev/null && "${parallel_binary_name}" --version &>/dev/null && [[ -z "${bats_no_parallelize_across_files}" ]]; then
     abort "Cannot execute \"${num_jobs}\" jobs without GNU parallel"
   fi
   # shellcheck source=lib/bats-core/semaphore.bash
-  source "${BATS_ROOT}/$BATS_LIBDIR/bats-core/semaphore.bash"
+  source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/semaphore.bash"
   bats_semaphore_setup
 fi
 
@@ -106,10 +106,10 @@ TESTS_LIST_FILE="${BATS_RUN_TMPDIR}/test_list_file.txt"
 
 TEST_ROOT=${1-}
 TEST_ROOT=${TEST_ROOT%/*}
-export BATS_RUN_LOGS_DIRECTORY="$TEST_ROOT/.bats/run-logs"
-if [[ ! -d "$BATS_RUN_LOGS_DIRECTORY" ]]; then
-  if [[ -n "$filter_status" ]]; then
-    printf "Error: --filter-status needs '%s/' to save failed tests. Please create this folder, add it to .gitignore and try again.\n" "$BATS_RUN_LOGS_DIRECTORY"
+export BATS_RUN_LOGS_DIRECTORY="${TEST_ROOT}/.bats/run-logs"
+if [[ ! -d "${BATS_RUN_LOGS_DIRECTORY}" ]]; then
+  if [[ -n "${filter_status}" ]]; then
+    printf "Error: --filter-status needs '%s/' to save failed tests. Please create this folder, add it to .gitignore and try again.\n" "${BATS_RUN_LOGS_DIRECTORY}"
     exit 1
   else
     BATS_RUN_LOGS_DIRECTORY=
@@ -119,42 +119,42 @@ if [[ ! -d "$BATS_RUN_LOGS_DIRECTORY" ]]; then
 else
   # use UTC (-u) to avoid problems with TZ changes
   BATS_RUNLOG_DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
-  export BATS_RUNLOG_FILE="$BATS_RUN_LOGS_DIRECTORY/${BATS_RUNLOG_DATE}.log" BATS_RUNLOG_DATE
-  if [[ ! -w "$BATS_RUN_LOGS_DIRECTORY" ]]; then
-    printf "WARNING: Cannot write in %s. This run will not write a log!\n" "$BATS_RUN_LOGS_DIRECTORY" >&2
+  export BATS_RUNLOG_FILE="${BATS_RUN_LOGS_DIRECTORY}/${BATS_RUNLOG_DATE}.log" BATS_RUNLOG_DATE
+  if [[ ! -w "${BATS_RUN_LOGS_DIRECTORY}" ]]; then
+    printf "WARNING: Cannot write in %s. This run will not write a log!\n" "${BATS_RUN_LOGS_DIRECTORY}" >&2
     BATS_RUNLOG_FILE='/dev/null' # disable runlog file
   fi
 fi
 
 # create file even if no tests are found so the `read` below won't fail
-touch "$TESTS_LIST_FILE"
-gather_tests_output=$(TESTS_LIST_FILE="$TESTS_LIST_FILE" filter="$filter" filter_status="$filter_status" bats-gather-tests "${gather_tests_flags[@]}" -- "$@")
-test_count=$(grep -c ^ "$TESTS_LIST_FILE" || true) # don't fail here when there are no tests
-if [[ $gather_tests_output == focus_mode ]]; then
+touch "${TESTS_LIST_FILE}"
+gather_tests_output=$(TESTS_LIST_FILE="${TESTS_LIST_FILE}" filter="${filter}" filter_status="${filter_status}" bats-gather-tests "${gather_tests_flags[@]}" -- "$@")
+test_count=$(grep -c ^ "${TESTS_LIST_FILE}" || true) # don't fail here when there are no tests
+if [[ ${gather_tests_output} == focus_mode ]]; then
   focus_mode=1
 else
   focus_mode=
 fi
 
-if [[ -n "$count_only_flag" ]]; then
+if [[ -n "${count_only_flag}" ]]; then
   printf '%d\n' "${test_count}"
   # we don't want to pollute the runlog files, as no tests would have been run
-  [[ $BATS_RUNLOG_FILE != /dev/null ]] && rm "$BATS_RUNLOG_FILE"
+  [[ ${BATS_RUNLOG_FILE} != /dev/null ]] && rm "${BATS_RUNLOG_FILE}"
   exit 0
 fi
 
-if [[ -n "$bats_no_parallelize_across_files" ]] && [[ ! "$num_jobs" -gt 1 ]]; then
+if [[ -n "${bats_no_parallelize_across_files}" ]] && [[ ! "${num_jobs}" -gt 1 ]]; then
   abort "The flag --no-parallelize-across-files requires at least --jobs 2"
 fi
 
-if [[ -n "$bats_no_parallelize_within_files" ]] && [[ ! "$num_jobs" -gt 1 ]]; then
+if [[ -n "${bats_no_parallelize_within_files}" ]] && [[ ! "${num_jobs}" -gt 1 ]]; then
   abort "The flag --no-parallelize-across-files requires at least --jobs 2"
 fi
 
 # only abort on the lowest levels
 trap 'BATS_INTERRUPTED=true' INT
 
-if [[ -n "$focus_mode" ]]; then
+if [[ -n "${focus_mode}" ]]; then
   printf "WARNING: This test run only contains tests tagged \`bats:focus\`!\n"
 fi
 
@@ -167,7 +167,7 @@ if [[ "${test_count}" == 0 ]]; then
 fi
 
 export BATS_SUITE_TMPDIR="${BATS_RUN_TMPDIR}/suite"
-if ! mkdir "$BATS_SUITE_TMPDIR"; then
+if ! mkdir "${BATS_SUITE_TMPDIR}"; then
   printf '%s\n' "Failed to create BATS_SUITE_TMPDIR" >&2
   exit 1
 fi
@@ -179,7 +179,7 @@ fi
 IFS=$'\n' read -d '' -r -a BATS_UNIQUE_TEST_FILENAMES < <(printf "%s\n" "$@" | nl | sort -k 2 | uniq -f 1 | sort -n | cut -f 2-) || true
 
 # shellcheck source=lib/bats-core/tracing.bash
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/tracing.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/tracing.bash"
 bats_setup_tracing
 
 trap bats_suite_exit_trap EXIT
@@ -203,19 +203,19 @@ bats_suite_exit_trap() {
     bats_exec_suite_status=1
   fi
 
-  if [[ -n "$print_bats_out" ]]; then
-    bats_prefix_lines_for_tap_output <"$BATS_OUT"
+  if [[ -n "${print_bats_out}" ]]; then
+    bats_prefix_lines_for_tap_output <"${BATS_OUT}"
   fi
 
   if [[ ${BATS_INTERRUPTED-NOTSET} != NOTSET ]]; then
     printf "\n# Received SIGINT, aborting ...\n\n"
   fi
 
-  if [[ -d "$BATS_RUN_LOGS_DIRECTORY" && -n "${BATS_INTERRUPTED:-}" ]]; then
+  if [[ -d "${BATS_RUN_LOGS_DIRECTORY}" && -n "${BATS_INTERRUPTED:-}" ]]; then
     # aborting a test run with CTRL+C does not save the runlog file
-    [[ "$BATS_RUNLOG_FILE" != /dev/null ]] && rm "$BATS_RUNLOG_FILE"
+    [[ "${BATS_RUNLOG_FILE}" != /dev/null ]] && rm "${BATS_RUNLOG_FILE}"
   fi
-  exit "$bats_exec_suite_status"
+  exit "${bats_exec_suite_status}"
 } >&3
 
 bats_run_teardown_suite() {
@@ -227,13 +227,13 @@ bats_run_teardown_suite() {
   bats_set_stacktrace_limit
 
   BATS_TEARDOWN_SUITE_COMPLETED=
-  teardown_suite >>"$BATS_OUT" 2>&1 || bats_teardown_suite_status=$?
+  teardown_suite >>"${BATS_OUT}" 2>&1 || bats_teardown_suite_status=$?
   if ((bats_teardown_suite_status == 0)); then
     BATS_TEARDOWN_SUITE_COMPLETED=1
   elif [[ -n "${BATS_SETUP_SUITE_COMPLETED:-}" ]]; then
     BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=1
-    BATS_ERROR_STATUS=$bats_teardown_suite_status
-    return $BATS_ERROR_STATUS
+    BATS_ERROR_STATUS=${bats_teardown_suite_status}
+    return "${BATS_ERROR_STATUS}"
   fi
 }
 
@@ -249,27 +249,27 @@ teardown_suite() {
 
 trap bats_teardown_suite_trap EXIT
 
-BATS_OUT="$BATS_RUN_TMPDIR/suite.out"
-if [[ -n "$setup_suite_file" ]]; then
+BATS_OUT="${BATS_RUN_TMPDIR}/suite.out"
+if [[ -n "${setup_suite_file}" ]]; then
   setup_suite() {
-    printf "%s does not define \`setup_suite()\`\n" "$setup_suite_file" >&2
+    printf "%s does not define \`setup_suite()\`\n" "${setup_suite_file}" >&2
     return 1
   }
 
   # shellcheck disable=SC2034 # will be used in the sourced file below
-  BATS_TEST_FILENAME="$setup_suite_file"
+  BATS_TEST_FILENAME="${setup_suite_file}"
   # shellcheck source=lib/bats-core/test_functions.bash
-  source "$BATS_ROOT/$BATS_LIBDIR/bats-core/test_functions.bash"
+  source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/test_functions.bash"
   _bats_test_functions_setup -1 # invalid TEST_NUMBER, as this is not a test
 
   # shellcheck disable=SC1090
-  source "$setup_suite_file"
+  source "${setup_suite_file}"
 
   bats_set_stacktrace_limit
 
   set -eET
   export BATS_SETUP_SUITE_COMPLETED=
-  setup_suite >>"$BATS_OUT" 2>&1
+  setup_suite >>"${BATS_OUT}" 2>&1
   BATS_SETUP_SUITE_COMPLETED=1
   set +ET
 else
@@ -278,12 +278,12 @@ else
   BATS_SETUP_SUITE_COMPLETED=1
 fi
 
-if [[ "$num_jobs" -gt 1 ]] && [[ -z "$bats_no_parallelize_across_files" ]]; then
+if [[ "${num_jobs}" -gt 1 ]] && [[ -z "${bats_no_parallelize_across_files}" ]]; then
   # run files in parallel to get the maximum pool of parallel tasks
   # shellcheck disable=SC2086,SC2068
   # we need to handle the quoting of ${flags[@]} ourselves,
   # because parallel can only quote it as one
-  "${parallel_binary_name}" --keep-order --jobs "$num_jobs" -- "bats-exec-file" "$(printf "%q " "${flags[@]}")" "{#}" "{}" "$TESTS_LIST_FILE" <<< "$(printf "%s\n" "${BATS_UNIQUE_TEST_FILENAMES[@]}")" 2>&1 || bats_exec_suite_status=1
+  "${parallel_binary_name}" --keep-order --jobs "${num_jobs}" -- "bats-exec-file" "$(printf "%q " "${flags[@]}")" "{#}" "{}" "${TESTS_LIST_FILE}" <<< "$(printf "%s\n" "${BATS_UNIQUE_TEST_FILENAMES[@]}")" 2>&1 || bats_exec_suite_status=1
 else
   file_index=0
   for filename in "${BATS_UNIQUE_TEST_FILENAMES[@]}"; do
@@ -292,14 +292,14 @@ else
       bats_exec_suite_status=130 # bash's code for SIGINT exits
       break
     fi
-    bats-exec-file "${flags[@]}" "$file_index" "$filename" "${TESTS_LIST_FILE}" || bats_exec_suite_status=1
+    bats-exec-file "${flags[@]}" "${file_index}" "${filename}" "${TESTS_LIST_FILE}" || bats_exec_suite_status=1
   done
 fi
 
 set -eET
 bats_run_teardown_suite
 
-if [[ "$focus_mode" == 1 && $bats_exec_suite_status -eq 0 ]]; then
+if [[ "${focus_mode}" == 1 && ${bats_exec_suite_status} -eq 0 ]]; then
   if [[ ${BATS_NO_FAIL_FOCUS_RUN-} == 1 ]]; then
     printf "WARNING: This test run only contains tests tagged \`bats:focus\`!\n"
   else
@@ -308,4 +308,4 @@ if [[ "$focus_mode" == 1 && $bats_exec_suite_status -eq 0 ]]; then
   fi
 fi
 
-exit "$bats_exec_suite_status" # the actual exit code will be set by the exit trap using bats_exec_suite_status
+exit "${bats_exec_suite_status}" # the actual exit code will be set by the exit trap using bats_exec_suite_status
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -51,39 +51,39 @@ export BATS_SUITE_TEST_NUMBER="$3"
 export BATS_TEST_NUMBER="$4"
 BATS_TEST_TRY_NUMBER="$5"
 
-if [[ -z "$BATS_TEST_FILENAME" ]]; then
+if [[ -z "${BATS_TEST_FILENAME}" ]]; then
   printf 'usage: bats-exec-test <filename>\n' >&2
   exit 1
-elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
-  printf 'bats: %s does not exist\n' "$BATS_TEST_FILENAME" >&2
+elif [[ ! -f "${BATS_TEST_FILENAME}" ]]; then
+  printf 'bats: %s does not exist\n' "${BATS_TEST_FILENAME}" >&2
   exit 1
 fi
 
 bats_create_test_tmpdirs() {
   local tests_tmpdir="${BATS_RUN_TMPDIR}/test"
-  if ! mkdir -p "$tests_tmpdir"; then
-    printf 'Failed to create: %s\n' "$tests_tmpdir" >&2
+  if ! mkdir -p "${tests_tmpdir}"; then
+    printf 'Failed to create: %s\n' "${tests_tmpdir}" >&2
     exit 1
   fi
 
-  BATS_TEST_TMPDIR="$tests_tmpdir/$BATS_SUITE_TEST_NUMBER"
-  if ! mkdir "$BATS_TEST_TMPDIR"; then
-    printf 'Failed to create BATS_TEST_TMPDIR%d: %s\n' "$BATS_TEST_TRY_NUMBER" "$BATS_TEST_TMPDIR" >&2
+  BATS_TEST_TMPDIR="${tests_tmpdir}/${BATS_SUITE_TEST_NUMBER}"
+  if ! mkdir "${BATS_TEST_TMPDIR}"; then
+    printf 'Failed to create BATS_TEST_TMPDIR%d: %s\n' "${BATS_TEST_TRY_NUMBER}" "${BATS_TEST_TMPDIR}" >&2
     exit 1
   fi
 
-  printf "%s\n" "$BATS_TEST_NAME" >> "$BATS_TEST_TMPDIR.name" # append name in case of test retries
+  printf "%s\n" "${BATS_TEST_NAME}" >> "${BATS_TEST_TMPDIR}.name" # append name in case of test retries
 
   export BATS_TEST_TMPDIR
 }
 
 # load the test helper functions like `load` or `run` that are needed to run a (preprocessed) .bats file without bash errors
 # shellcheck source=lib/bats-core/test_functions.bash disable=SC2153
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/test_functions.bash"
-_bats_test_functions_setup "$BATS_TEST_NUMBER"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/test_functions.bash"
+_bats_test_functions_setup "${BATS_TEST_NUMBER}"
 
 # shellcheck source=lib/bats-core/tracing.bash disable=SC2153
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/tracing.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/tracing.bash"
 
 bats_teardown_trap() {
   bats_check_status_from_trap
@@ -100,20 +100,20 @@ bats_teardown_trap() {
   # parameter 1 will signify the reason why this function was called
   # this is used to identify when this is called as exit trap function
   BATS_TEARDOWN_STARTED=${1:-1}
-  teardown >>"$BATS_OUT" 2>&1 || bats_teardown_trap_status="$?"
+  teardown >>"${BATS_OUT}" 2>&1 || bats_teardown_trap_status="$?"
 
-  if [[ $bats_teardown_trap_status -eq 0 ]]; then
+  if [[ ${bats_teardown_trap_status} -eq 0 ]]; then
     BATS_TEARDOWN_COMPLETED=1
-  elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
+  elif [[ -n "${BATS_TEST_COMPLETED}" ]]; then
     BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=1
-    BATS_ERROR_STATUS="$bats_teardown_trap_status"
+    BATS_ERROR_STATUS="${bats_teardown_trap_status}"
   fi
 
-  bats_exit_trap "$killer_pid"
+  bats_exit_trap "${killer_pid}"
 }
 
 # shellcheck source=lib/bats-core/common.bash
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/common.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/common.bash"
 
 bats_exit_trap() {
   local status
@@ -122,20 +122,20 @@ bats_exit_trap() {
   trap - ERR EXIT
   if [[ -n "${BATS_TEST_TIMEOUT:-}" ]]; then
     # Kill the watchdog in the case of of kernel finished before the timeout
-    bats_abort_timeout_countdown "$killer_pid" || status=1
+    bats_abort_timeout_countdown "${killer_pid}" || status=1
   fi
 
-  if [[ -n "$BATS_TEST_SKIPPED" ]]; then
+  if [[ -n "${BATS_TEST_SKIPPED}" ]]; then
     exit_metadata=' # skip'
-    if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
-      exit_metadata+=" $BATS_TEST_SKIPPED"
+    if [[ "${BATS_TEST_SKIPPED}" != '1' ]]; then
+      exit_metadata+=" ${BATS_TEST_SKIPPED}"
     fi
   elif [[ "${BATS_TIMED_OUT-NOTSET}" != NOTSET ]]; then
     exit_metadata=" # timeout after ${BATS_TEST_TIMEOUT}s"
   fi
 
   BATS_TEST_TIME=''
-  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
+  if [[ -n "${BATS_ENABLE_TIMING}" ]]; then
     get_mills_since_epoch BATS_TEST_END_TIME
     BATS_TEST_TIME=" in "$((BATS_TEST_END_TIME - BATS_TEST_START_TIME))"ms"
   fi
@@ -143,8 +143,8 @@ bats_exit_trap() {
   local print_bats_out="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS}"
 
   local should_retry=''
-  if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" || "${BATS_INTERRUPTED-NOTSET}" != NOTSET ]]; then
-    if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
+  if [[ -z "${BATS_TEST_COMPLETED}" || -z "${BATS_TEARDOWN_COMPLETED}" || "${BATS_INTERRUPTED-NOTSET}" != NOTSET ]]; then
+    if [[ ""${BATS_ERROR_STATUS}"" -eq 0 ]]; then
       # For some versions of bash, `$?` may not be set properly for some error
       # conditions before triggering the EXIT trap directly (see #72 and #81).
       # Thanks to the `BATS_TEARDOWN_COMPLETED` signal, this will pinpoint such
@@ -159,9 +159,9 @@ bats_exit_trap() {
     if bats_should_retry_test; then
       should_retry=1
       status=126                # signify retry
-      rm -r "$BATS_TEST_TMPDIR" # clean up for retry
+      rm -r "${BATS_TEST_TMPDIR}" # clean up for retry
     else
-      printf 'not ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" "$exit_metadata" >&3
+      printf 'not ok %d %s%s\n' "${BATS_SUITE_TEST_NUMBER}" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" "${exit_metadata}" >&3
       if (( ${#BATS_TEST_TAGS[@]} > 0 )); then
         printf '# tags:'
         printf ' %s' "${BATS_TEST_TAGS[@]}"
@@ -172,42 +172,42 @@ bats_exit_trap() {
       bats_print_stack_trace "${stack_trace[@]}" >&3
       bats_print_failed_command "${stack_trace[@]}" >&3
 
-      if [[ $BATS_PRINT_OUTPUT_ON_FAILURE ]]; then
+      if [[ ${BATS_PRINT_OUTPUT_ON_FAILURE} ]]; then
         if [[ -n "${output:-}" ]]; then
-          printf "Last output:\n%s\n" "$output"
+          printf "Last output:\n%s\n" "${output}"
         fi
         if [[ -n "${stderr:-}" ]]; then
-          printf "Last stderr: \n%s\n" "$stderr"
+          printf "Last stderr: \n%s\n" "${stderr}"
         fi
-      fi >>"$BATS_OUT"
+      fi >>"${BATS_OUT}"
 
       print_bats_out=1
       status=1
       local state=failed
     fi
   else
-    printf 'ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
-      "$exit_metadata" >&3
+    printf 'ok %d %s%s\n' "${BATS_SUITE_TEST_NUMBER}" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
+      "${exit_metadata}" >&3
     status=0
     local state=passed
   fi
 
-  if [[ -z "$should_retry" ]]; then
-    printf "%s %s\t%s\n" "$state" "$BATS_TEST_FILENAME" "$BATS_TEST_NAME" >>"$BATS_RUNLOG_FILE"
+  if [[ -z "${should_retry}" ]]; then
+    printf "%s %s\t%s\n" "${state}" "${BATS_TEST_FILENAME}" "${BATS_TEST_NAME}" >>"${BATS_RUNLOG_FILE}"
 
-    if [[ $print_bats_out ]]; then
-      bats_prefix_lines_for_tap_output <"$BATS_OUT" | bats_replace_filename >&3
+    if [[ ${print_bats_out} ]]; then
+      bats_prefix_lines_for_tap_output <"${BATS_OUT}" | bats_replace_filename >&3
     fi
   fi
-  if [[ $BATS_GATHER_TEST_OUTPUTS_IN ]]; then
+  if [[ ${BATS_GATHER_TEST_OUTPUTS_IN} ]]; then
     local try_suffix=
-    if [[ -n "$should_retry" ]]; then
-      try_suffix="-try$BATS_TEST_TRY_NUMBER"
+    if [[ -n "${should_retry}" ]]; then
+      try_suffix="-try${BATS_TEST_TRY_NUMBER}"
     fi
-    cp "$BATS_OUT" "$BATS_GATHER_TEST_OUTPUTS_IN/$BATS_SUITE_TEST_NUMBER$try_suffix-${BATS_TEST_DESCRIPTION//\//%2F}.log"
+    cp "${BATS_OUT}" "${BATS_GATHER_TEST_OUTPUTS_IN}/${BATS_SUITE_TEST_NUMBER}${try_suffix}-${BATS_TEST_DESCRIPTION//\//%2F}.log"
   fi
-  rm -f "$BATS_OUT"
-  exit "$status"
+  rm -f "${BATS_OUT}"
+  exit "${status}"
 }
 
 # Marks the test as failed due to timeout.
@@ -226,30 +226,30 @@ bats_get_child_processes_of() { # <parent-pid>
     read -ra header
     local pid_col ppid_col
     for ((i = 0; i < ${#header[@]}; ++i)); do
-      if [[ ${header[$i]} == "PID" ]]; then
-        pid_col=$i
+      if [[ ${header[${i}]} == "PID" ]]; then
+        pid_col=${i}
       fi
-      if [[ ${header[$i]} == "PPID" ]]; then
-        ppid_col=$i
+      if [[ ${header[${i}]} == "PPID" ]]; then
+        ppid_col=${i}
       fi
     done
     while read -ra row; do
-      if ((${row[$ppid_col]} == parent_pid)); then
-        printf "%d\n" "${row[$pid_col]}"
+      if ((${row[${ppid_col}]} == parent_pid)); then
+        printf "%d\n" "${row[${pid_col}]}"
       fi
     done
-  } < <(ps -ef "$parent_pid")
+  } < <(ps -ef "${parent_pid}")
 }
 
 bats_kill_childprocesses_of() { # <parent-pid>
   local -ir parent_pid="${1?}"
   if command -v pkill; then
-    pkill -P "$parent_pid"
+    pkill -P "${parent_pid}"
   else
     # kill in reverse order (latest first)
     while read -r pid; do
-      kill "$pid"
-    done < <(bats_get_child_processes_of "$parent_pid" | sort -r)
+      kill "${pid}"
+    done < <(bats_get_child_processes_of "${parent_pid}" | sort -r)
   fi >/dev/null
 }
 
@@ -265,22 +265,22 @@ bats_start_timeout_countdown() { # <timeout>
   local -ri timeout=$1
   local -ri target_pid=$$
   # shellcheck disable=SC2064
-  trap "bats_timeout_trap $target_pid" ABRT
+  trap "bats_timeout_trap ${target_pid}" ABRT
   if ! (command -v ps || command -v pkill) >/dev/null; then
     printf "Error: Cannot execute timeout because neither pkill nor ps are available on this system!\n" >&2
     exit 1
   fi
   # Start another process to kill the children of this process
   (
-    sleep "$timeout" &
+    sleep "${timeout}" &
     # sleep won't receive signals, so we use wait below
     # and kill sleep explicitly when signalled to do so
     # shellcheck disable=SC2064
     trap "kill $!; exit 0" ABRT
     wait
-    if kill -ABRT "$target_pid"; then
+    if kill -ABRT "${target_pid}"; then
       # get rid of signal blocking child processes (like sleep)
-      bats_kill_childprocesses_of "$target_pid"
+      bats_kill_childprocesses_of "${target_pid}"
     fi &>/dev/null
   ) &
 }
@@ -296,28 +296,28 @@ get_mills_since_epoch() { # <output-variable>
   local -r output_variable="$1"
   local int frac
   # allow for different decimal separators
-  IFS=., read -r int frac <<<"$EPOCHREALTIME"
-  printf -v "$output_variable" "%d" "${int}${frac::3}"
+  IFS=., read -r int frac <<<"${EPOCHREALTIME}"
+  printf -v "${output_variable}" "%d" "${int}${frac::3}"
 }
 else
 get_mills_since_epoch() { # <output-variable>
   local -r output_variable="$1"
   local ms_since_epoch
   ms_since_epoch=$(bats_execute date +%s%N)
-  if [[ "$ms_since_epoch" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
+  if [[ "${ms_since_epoch}" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
     ms_since_epoch=$(($(bats_execute date +%s) * 1000))
   else
     ms_since_epoch=$((ms_since_epoch / 1000000))
   fi
-  printf -v "$output_variable" "%d" "$ms_since_epoch"
+  printf -v "${output_variable}" "%d" "${ms_since_epoch}"
 }
 fi
 
 bats_perform_test() {
   if ! declare -F "${BATS_TEST_NAME%% *}" &>/dev/null; then
     local quoted_test_name
-    bats_quote_code quoted_test_name "$BATS_TEST_NAME"
-    printf "bats: unknown test name %s\n" "$quoted_test_name" >&2
+    bats_quote_code quoted_test_name "${BATS_TEST_NAME}"
+    printf "bats: unknown test name %s\n" "${quoted_test_name}" >&2
     exit 1
   fi
 
@@ -326,13 +326,13 @@ bats_perform_test() {
     # forward skip (with message) by overriding setup
     # shellcheck disable=SC2317
     setup() {
-      skip "$BATS_TEST_SKIPPED"
+      skip "${BATS_TEST_SKIPPED}"
     }
   fi
 
   local BATS_killer_pid=''
   if [[ -n "${BATS_TEST_TIMEOUT:-}" ]]; then
-    bats_start_timeout_countdown "$BATS_TEST_TIMEOUT"
+    bats_start_timeout_countdown "${BATS_TEST_TIMEOUT}"
     BATS_killer_pid=$!
   fi
   BATS_TEST_COMPLETED=
@@ -342,10 +342,10 @@ bats_perform_test() {
   bats_setup_tracing
   # use parameter to mark this call as trap call
   # shellcheck disable=SC2064
-  trap "bats_teardown_trap as-exit-trap $BATS_killer_pid" EXIT
+  trap "bats_teardown_trap as-exit-trap ${BATS_killer_pid}" EXIT
 
-  if [[ -n "$BATS_EXTENDED_SYNTAX" ]]; then
-    printf 'begin %d %s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}$BATS_TEST_DESCRIPTION" >&3
+  if [[ -n "${BATS_EXTENDED_SYNTAX}" ]]; then
+    printf 'begin %d %s\n' "${BATS_SUITE_TEST_NUMBER}" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}" >&3
   fi
 
   get_mills_since_epoch BATS_TEST_START_TIME
@@ -353,21 +353,21 @@ bats_perform_test() {
     bats_set_stacktrace_limit
     setup "$@"
     "$@"
-  } >>"$BATS_OUT" 2>&1 4>&1
+  } >>"${BATS_OUT}" 2>&1 4>&1
 
   BATS_TEST_COMPLETED=1
   # shellcheck disable=SC2064
-  trap "bats_exit_trap $BATS_killer_pid" EXIT
-  bats_teardown_trap "" "$BATS_killer_pid" # pass empty parameter to signify call outside trap
+  trap "bats_exit_trap ${BATS_killer_pid}" EXIT
+  bats_teardown_trap "" "${BATS_killer_pid}" # pass empty parameter to signify call outside trap
 }
 
 trap bats_interrupt_trap INT
 
 # shellcheck source=lib/bats-core/preprocessing.bash
-source "$BATS_ROOT/$BATS_LIBDIR/bats-core/preprocessing.bash"
+source "${BATS_ROOT}/${BATS_LIBDIR}/bats-core/preprocessing.bash"
 
 exec 3<&1
-BATS_OUT="$BATS_RUN_TMPDIR/test/$BATS_SUITE_TEST_NUMBER.out"
+BATS_OUT="${BATS_RUN_TMPDIR}/test/${BATS_SUITE_TEST_NUMBER}.out"
 
 bats_create_test_tmpdirs
 bats_evaluate_preprocessed_source
