[master] continuing work

diff --git a/scripts/clone-bats-repos b/scripts/clone-bats-repos
--- a/scripts/clone-bats-repos
+++ b/scripts/clone-bats-repos
@@ -113,7 +113,7 @@ function usage
   into a specified directory.
   Usage: ${SCRIPT} -d,--dir [directory] -h,--help
   -d,--dir  Specifies the directory into which the bats-core repositories will
-            be cloned.  If the direcotry does not exist, it will be created.
+            be cloned.  If the directory does not exist, it will be created.
             Required.
   -h,--help Prints this usage information and exits. Takes precedence over all
             other options. Optional.
@@ -206,6 +206,27 @@ function parse_command_line_options
   fi
 }
 
+# ${1} - submodule git repository url
+# ${2} - full path to submodule destination directory
+function add_submodule
+{
+  pushd "${PWD}"
+  local -r sub_parent_dir="$(dirname "${2}")"
+  cd "${sub_parent_dir}"
+  local -r sub_dir="$(basename "${2}")"
+  git submodule add "${1}" "${sub_dir}"
+  local -ir stat=${?}
+  if [[ 0 -eq ${stat} ]]
+  then
+    log_info "Cloned submodule [${1}] into [${2}]." "${LINENO}"
+    echo ''
+  else
+    log_error "Failed to clone submodule [${1}] into [${2}] due to error code [${stat}]. Exiting." "${LINENO}"
+    exit 1
+  fi
+  popd > /dev/null
+}
+
 function clone_bats_core_repos
 {
   local -i stat=0
@@ -215,43 +236,33 @@ function clone_bats_core_repos
     stat=${?}
     if [[ 0 -ne ${stat} ]]
     then
-      log_error "Failed to create directory [${REPOS_DIR}] due to error code [${stat}]. Exiting." "${LINENO}"
+      log_error "Failed to create new directory [${REPOS_DIR}] due to error code [${stat}]. Exiting." "${LINENO}"
       exit 1
     fi
   fi
 
-  cd "${REPOS_DIR}"
-  if [[ -d "${BATS_CORE}" ]]
+  local -r bats_core_repo="${REPOS_DIR}/${BATS_CORE}"
+  if [[ -d "${bats_core_repo}" ]]
   then
-    log_error "The bats-core repository [${REPOS_DIR}/${BATS_CORE}] already exists. Exiting."
+    log_error "The bats-core repository [${bats_core_repo}] already exists. Exiting."
     exit 1
   fi
 
-  git clone "${BATS_CORE_URL}" "${BATS_CORE}"
+  git clone "${BATS_CORE_URL}" "${bats_core_repo}"
   stat=${?}
   if [[ 0 -eq ${stat} ]]
   then
-    log_info "Cloned [${BATS_CORE_URL}] into [${REPOS_DIR}/${BATS_CORE}]." "${LINENO}"
+    log_info "Cloned [${BATS_CORE_URL}] into [${bats_core_repo}]." "${LINENO}"
+    echo ''
   else
-    log_error "Failed to clone [${BATS_CORE_URL}] into [${REPOS_DIR}/${BATS_CORE}] due to error code [${stat}]. Exiting." "${LINENO}"
+    log_error "Failed to clone [${BATS_CORE_URL}] into [${bats_core_repo}] due to error code [${stat}]. Exiting." "${LINENO}"
     exit 1
   fi
 
-  cd "${BATS_CORE}"
   local key
-  local module_path
-  for key in "${!BATS_LIB_REPOS[@]}"
+  for key in $(echo "${!BATS_LIB_REPOS[@]}" | tr ' ' '\n' | sort)
   do
-    module_path=${REPOS_DIR}/${BATS_CORE}/${key}
-    git submodule add "${BATS_LIB_REPOS[${key}]}" "${key}"
-    stat=${?}
-    if [[ 0 -eq ${stat} ]]
-    then
-      log_info "Cloned [${BATS_LIB_REPOS[${key}]}] into [${module_path}]." "${LINENO}"
-    else
-      log_error "Failed to clone [${BATS_LIB_REPOS[${key}]}] into [${module_path}] due to error code [${stat}]. Exiting." "${LINENO}"
-      exit 1
-    fi
+    add_submodule "${BATS_LIB_REPOS[${key}]}" "${bats_core_repo}/${key}"
   done
 }
 
